name: Format Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pre-commit
    
    - name: Check Black formatting
      run: black --line-length 88 --target-version py38 --check .
    
    - name: Run pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files
