attention_resolutions: 16,8
class_cond: false
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 128
num_head_channels: 32
num_heads: 2
num_res_blocks: 1
resblock_updown: true
use_fp16: true
use_scale_shift_norm: true
classifier_scale: 2.0
lr_kernel_n_std: 2
num_samples: 1
show_progress: true
timestep_respacing: '10'
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: true
classifier_width: 64
classifier_depth: 1
classifier_attention_resolutions: 16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: true
use_new_attention_order: false
clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 128
model_path: ./data/pretrained/celeba256_250000.pt
name: oai_test_celeba_balanced_4_gpu_optimized
inpa_inj_sched_prev: true
n_jobs: 1
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 10
  n_sample: 1
  jump_length: 2
  jump_n_sample: 2
data:
  eval:
    oai_test_celeba_balanced_4_gpu_optimized:
      mask_loader: true
      gt_path: /tmp/oai_balanced_4/img
      mask_path: /tmp/oai_balanced_4/mask_inv
      image_size: 128
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      offset: 0
      max_len: 4
      paths:
        srs: ../OAI_dataset/output/RePaint_CelebA_4/inpainted
        lrs: ../OAI_dataset/output/RePaint_CelebA_4/gt_masked
        gts: ../OAI_dataset/output/RePaint_CelebA_4/gt
        gt_keep_masks: ../OAI_dataset/output/RePaint_CelebA_4/gt_keep_mask
