# RePaint configuration for OAI dataset testing (CPU VERSION)
# Optimized for CPU-only execution

attention_resolutions: 8,4
class_cond: false
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 64  # Very small for CPU
num_head_channels: 16
num_heads: 1
num_res_blocks: 1
resblock_updown: true
use_fp16: false  # Disable FP16 for CPU
use_scale_shift_norm: true
classifier_scale: 4.0
lr_kernel_n_std: 2
num_samples: 1  # Test only 1 image
show_progress: true
timestep_respacing: '5'  # Very fast: 5 steps
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: false
classifier_width: 32
classifier_depth: 1
classifier_attention_resolutions: 8,4
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: true
use_new_attention_order: false
clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 64  # Very small for CPU
model_path: ./data/pretrained/places256_300000.pt
name: oai_test_cpu
inpa_inj_sched_prev: true
n_jobs: 1
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 5  # Match timestep_respacing
  n_sample: 1
  jump_length: 1
  jump_n_sample: 1
data:
  eval:
    oai_test_cpu:
      mask_loader: true
      gt_path: ../OAI_dataset/test/img
      mask_path: ../OAI_dataset/test/mask_inv
      image_size: 64
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      offset: 0
      max_len: 1  # Only 1 image
      paths:
        srs: ../OAI_dataset/output/RePaint_Places_cpu/inpainted
        lrs: ../OAI_dataset/output/RePaint_Places_cpu/gt_masked
        gts: ../OAI_dataset/output/RePaint_Places_cpu/gt
        gt_keep_masks: ../OAI_dataset/output/RePaint_Places_cpu/gt_keep_mask
