# RePaint configuration for OAI dataset testing (MEMORY OPTIMIZED)
# Uses original architecture but with memory optimizations

attention_resolutions: 32,16,8
class_cond: false
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_heads: 4
num_res_blocks: 2
resblock_updown: true
use_fp16: true  # Enable FP16 to save memory
use_scale_shift_norm: true
classifier_scale: 4.0
lr_kernel_n_std: 2
num_samples: 1  # Test only 1 image at a time
show_progress: true
timestep_respacing: '50'  # Faster: 50 steps instead of 250
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: true  # Enable FP16 for classifier
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: true  # Enable checkpointing to save memory
use_new_attention_order: false
clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 256
model_path: ./data/pretrained/places256_300000.pt
name: oai_test_memory_optimized
inpa_inj_sched_prev: true
n_jobs: 1
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 50  # Match timestep_respacing
  n_sample: 1
  jump_length: 5  # Reduced for faster processing
  jump_n_sample: 5  # Reduced for faster processing
data:
  eval:
    oai_test_memory_optimized:
      mask_loader: true
      gt_path: ../OAI_dataset/test/img
      mask_path: ../OAI_dataset/test/mask_inv
      image_size: 256
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      offset: 0
      max_len: 1  # Only 1 image
      paths:
        srs: ../OAI_dataset/output/RePaint_Places_memory_optimized/inpainted
        lrs: ../OAI_dataset/output/RePaint_Places_memory_optimized/gt_masked
        gts: ../OAI_dataset/output/RePaint_Places_memory_optimized/gt
        gt_keep_masks: ../OAI_dataset/output/RePaint_Places_memory_optimized/gt_keep_mask
