# RePaint configuration for OAI dataset testing (FAST VERSION)
# Optimized for limited GPU memory (4GB)

attention_resolutions: 16,8,4
class_cond: false
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 128  # Reduced from 256
num_head_channels: 32  # Reduced from 64
num_heads: 2  # Reduced from 4
num_res_blocks: 1  # Reduced from 2
resblock_updown: true
use_fp16: true  # Enable FP16 to save memory
use_scale_shift_norm: true
classifier_scale: 4.0
lr_kernel_n_std: 2
num_samples: 22  # Number of test images
show_progress: true
timestep_respacing: '10'  # Very fast: 10 steps instead of 25
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: true  # Enable FP16 for classifier
classifier_width: 64  # Reduced from 128
classifier_depth: 1  # Reduced from 2
classifier_attention_resolutions: 16,8,4
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: true  # Enable checkpointing to save memory
use_new_attention_order: false
clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 128  # Reduced from 256 to 128
model_path: ./data/pretrained/places256_300000.pt
name: oai_test_fast
inpa_inj_sched_prev: true
n_jobs: 1
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 10  # Match timestep_respacing
  n_sample: 1
  jump_length: 2  # Reduced for faster processing
  jump_n_sample: 2  # Reduced for faster processing
data:
  eval:
    oai_test_fast:
      mask_loader: true
      gt_path: ../OAI_dataset/test/img
      mask_path: ../OAI_dataset/test/mask_inv
      image_size: 128  # Reduced from 256
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      offset: 0
      max_len: 22  # Number of test images
      paths:
        srs: ../OAI_dataset/output/RePaint_Places_fast/inpainted
        lrs: ../OAI_dataset/output/RePaint_Places_fast/gt_masked
        gts: ../OAI_dataset/output/RePaint_Places_fast/gt
        gt_keep_masks: ../OAI_dataset/output/RePaint_Places_fast/gt_keep_mask
